In [1]:
%load_ext autoreload
%autoreload 2
%run nnn/ipynb_init.py
%matplotlib inline

In [5]:
complexes = pd.read_csv("./data/uv_melt/ECLTables/ECLComplexes_230208.csv")

In [6]:
seqid_complexes = complexes.query('Group == "order90" & Type == "hairpin"').SEQID.tolist()#.apply(lambda x: x.strip()).tolist()

In [7]:
seqid_complexes

['BC0',
 'BC1',
 'BC6',
 'BC7',
 'BC8',
 'BC9',
 'BC10',
 'BC11',
 'MMTM177',
 'MMCNNN2328',
 'MMCNNN2331',
 'MMCNNN2334',
 'MMCNNN2335',
 'MMCNNN2336',
 'MMCNNN2337',
 'MMTM1325',
 'MMTM176',
 'MMTM178',
 'MMTM179',
 'MMTM181',
 'MMTM185',
 'MMTM189',
 'MMTM1917',
 'MMTM29',
 'MMTM397',
 'MMTM509',
 'MMTM877',
 'TETNN903',
 'TETNN966',
 'TETNN964',
 'TETNN836',
 'TETNN839',
 'TETNN965',
 'TETNN837',
 'TETNN773',
 'TETNN967',
 'TETNN900',
 'TETNN838',
 'TETNN901',
 'TETNN902',
 'TETNN772',
 'TETNN774',
 'TETNN775',
 'TETNN1011',
 'TETNN987',
 'TETNN983',
 'TETNN995',
 'TETNN1019',
 'TETNN1015',
 'TETNN971',
 'TETNN1003',
 'TETNN975',
 'TETNN999',
 'TETNN1007',
 'TETNN1023',
 'TETNN963',
 'TETNN979',
 'TETNN991',
 'TETNNN3905',
 'TETNNN1640',
 'TETNNN1848',
 'TETNNN615',
 'TETNNN1847',
 'TETNNN707',
 'TETNNN621',
 'TETNNN2364',
 'TETNNN2229',
 'TETNNN757',
 'TETNNN2253',
 'TETNNN1781',
 'TETNNN2108',
 'TETNNN1696',
 'TETNNN2082',
 'TETNNN3186',
 'TETNNN2099',
 'TETNNN1570']

In [41]:
n_exp = np.ceil(len(seqid_complexes) / 6).astype(int)
sample_sheet = pd.DataFrame(columns=['curve_date', 'TODO', 'curve_num', 'BlankTo', 
                                    'SEQID', 'conc_uM', 'TotalVolume'])
for i in range(n_exp):
    seqs = seqid_complexes[6*i:6*i + 6]
    seqs += ["blank"] * (7 - len(seqs))
    exp_dict = dict(
        curve_date = "order90_%02d" % (i+1),
        TODO = True,
        curve_num = np.arange(7, dtype=int) + 1,
        BlankTo = int(7),
        SEQID =  seqs,
        conc_uM = 6,
        TotalVolume = 300
    )
    df = pd.DataFrame(exp_dict)
    sample_sheet = pd.concat([sample_sheet, df], axis=0)
    
sample_sheet.to_csv("./data/uv_melt/ECLTables/ECLSampleSheet230201.csv")
sample_sheet

    curve_date  TODO curve_num BlankTo           SEQID conc_uM TotalVolume
0   order90_01  True         1       7         \nBC0\n       6         300
1   order90_01  True         2       7         \nBC1\n       6         300
2   order90_01  True         3       7         \nBC6\n       6         300
3   order90_01  True         4       7         \nBC7\n       6         300
4   order90_01  True         5       7         \nBC8\n       6         300
..         ...   ...       ...     ...             ...     ...         ...
2   order90_13  True         3       7  \nTETNNN2099\n       6         300
3   order90_13  True         4       7  \nTETNNN1570\n       6         300
4   order90_13  True         5       7           blank       6         300
5   order90_13  True         6       7           blank       6         300
6   order90_13  True         7       7           blank       6         300

[91 rows x 7 columns]

## Make sample sheet for the failed ones

In [25]:
complexes = pd.read_csv("./data/uv_melt/ECLTables/ECLComplexes_230208.csv")
complexes['measured'] = complexes['ProtocolID (from curve_date) (from ECLSampleSheet)'].apply(lambda x: isinstance(x, str))
seqid_complexes = complexes.query('(Group == "order90" | Group == "test_hp1") & Type == "hairpin" & measured & DataAvailable == "False"').SEQID.tolist()

,SEQID,StrandA,StrandB,ss_conc_uM,Type,DataAvailable,ECLSampleSheet,StrandA_SampleID,StrandB_SampleID,Purification,GivenUp,Group,ProtocolID (from curve_date) (from ECLSampleSheet),measured
112,WC68,WC68,NaN,128.0,hairpin,False,"12,13,14,15,16,17,18,143","Object[Sample, ""id:Y0lXejMpm8oP""]",NaN,standard desalting,False,WC24,"Object[Protocol, UVMelting, ""id:wqW9BPWv9J7M""]...",True
113,WC1106,WC1106,NaN,128.0,hairpin,False,"19,144","Object[Sample, ""id:N80DNj1JzN4o""]",NaN,standard desalting,False,WC24,"Object[Protocol, UVMelting, ""id:6V0npv08lGpZ""]...",True
121,WC1432,WC1432,NaN,128.0,hairpin,False,"41,145","Object[Sample, ""id:4pO6dM5L9Mv8""]",NaN,standard desalting,False,WC24,"Object[Protocol, UVMelting, ""id:J8AY5jAx11vE""]...",True
123,WC2922,WC2922,NaN,128.0,hairpin,False,"43,147","Object[Sample, ""id:pZx9jo8X7BKj""]",NaN,standard desalting,False,WC24,"Object[Protocol, UVMelting, ""id:J8AY5jAx11vE""]...",True
124,WC91,WC91,NaN,128.0,hairpin,False,"44,148","Object[Sample, ""id:dORYzZJ85Mpb""]",NaN,standard desalting,False,WC24,"Object[Protocol, UVMelting, ""id:J8AY5jAx11vE""]...",True
125,WC2119,WC2119,NaN,128.0,hairpin,False,"45,149","Object[Sample, ""id:bq9LA0JDprPa""]",NaN,standard desalting,False,WC24,"Object[Protocol, UVMelting, ""id:J8AY5jAx11vE""]...",True
126,WC2215,WC2215,NaN,128.0,hairpin,False,"46,150","Object[Sample, ""id:Z1lqpMzVdkKW""]",NaN,standard desalting,False,WC24,"Object[Protocol, UVMelting, ""id:J8AY5jAx11vE""]...",True

In [38]:
# Fill up the spots with other failed samples
seqid_complexes = seqid_complexes + \
    complexes.query('(Group != "order90" & Group != "test_hp1") & Type == "hairpin" & measured & DataAvailable == "False" & (GivenUp != True)').SEQID.tolist()[:3]

In [41]:
n_exp = np.ceil(len(seqid_complexes) / 6).astype(int)
sample_sheet = pd.DataFrame(columns=['curve_date', 'TODO', 'curve_num',# 'BlankTo', 
                                    'SEQID', 'conc_uM', 'TotalVolume'])
for i in range(n_exp):
    seqs = seqid_complexes[6*i:6*i + 6]
    seqs += ["blank"] * (7 - len(seqs))
    exp_dict = dict(
        curve_date = "test_hp_bae_rerun_%02d" % (i+1),
        TODO = True,
        curve_num = np.arange(7, dtype=int) + 1,
        SEQID =  seqs,
        conc_uM = 6,
        TotalVolume = 300
    )
    df = pd.DataFrame(exp_dict)
    sample_sheet = pd.concat([sample_sheet, df], axis=0)
    
sample_sheet.to_csv("./data/uv_melt/ECLTables/ECLSampleSheet230208.csv")
sample_sheet

             curve_date  TODO curve_num   SEQID conc_uM TotalVolume
0  test_hp_bae_rerun_01  True         1     BC0       6         300
1  test_hp_bae_rerun_01  True         2     BC1       6         300
2  test_hp_bae_rerun_01  True         3     BC6       6         300
3  test_hp_bae_rerun_01  True         4     BC7       6         300
4  test_hp_bae_rerun_01  True         5     BC8       6         300
5  test_hp_bae_rerun_01  True         6     BC9       6         300
6  test_hp_bae_rerun_01  True         7   blank       6         300
0  test_hp_bae_rerun_02  True         1   HP001       6         300
1  test_hp_bae_rerun_02  True         2   HP002       6         300
2  test_hp_bae_rerun_02  True         3   HP003       6         300
3  test_hp_bae_rerun_02  True         4   HP004       6         300
4  test_hp_bae_rerun_02  True         5   HP005       6         300
5  test_hp_bae_rerun_02  True         6   HP006       6         300
6  test_hp_bae_rerun_02  True         7   blank       6         300
0  test_hp_bae_rerun_03  True         1   HP008       6         300
1  test_hp_bae_rerun_03  True         2   HP010       6         300
2  test_hp_bae_rerun_03  True         3   HP012       6         300
3  test_hp_bae_rerun_03  True         4   HP022       6         300
4  test_hp_bae_rerun_03  True         5   HP038       6         300
5  test_hp_bae_rerun_03  True         6   HP039       6         300
6  test_hp_bae_rerun_03  True         7   blank       6         300
0  test_hp_bae_rerun_04  True         1   HP040       6         300
1  test_hp_bae_rerun_04  True         2   HP041       6         300
2  test_hp_bae_rerun_04  True         3   HP042       6         300
3  test_hp_bae_rerun_04  True         4   HP043       6         300
4  test_hp_bae_rerun_04  True         5   HP044       6         300
5  test_hp_bae_rerun_04  True         6   HP045       6         300
6  test_hp_bae_rerun_04  True         7   blank       6         300
0  test_hp_bae_rerun_05  True         1   HP046       6         300
1  test_hp_bae_rerun_05  True         2   HP047       6         300
2  test_hp_bae_rerun_05  True         3   HP048       6         300
3  test_hp_bae_rerun_05  True         4    WC68       6         300
4  test_hp_bae_rerun_05  True         5  WC1106       6         300
5  test_hp_bae_rerun_05  True         6  WC1432       6         300
6  test_hp_bae_rerun_05  True         7   blank       6         300

## 03/10/2023

Design duplex UV melting experiments at 8uM and 16uM.

In [21]:
duplexes = pd.read_clipboard(header=None).values.flatten()

In [22]:
duplexes

array(['WC68_stem', 'WC1025_split', 'DMM003', 'DMM004', 'DMM005',
       'DBG001', 'DBG002', 'DBG003', 'DBG004', 'DBG005', 'DBG006',
       'DBG007', 'DMM003_ref', 'DMM004_ref', 'DMM005_ref', 'DMM007_ref',
       'DBG001_ref', 'DBG002_ref', 'DBG003_ref', 'DBG004_ref',
       'DBG005_ref', 'DBG006_ref', 'DBG007_ref'], dtype=object)

In [23]:
np.random.shuffle(duplexes)

In [24]:
duplexes

array(['DBG003_ref', 'WC1025_split', 'DBG001', 'WC68_stem', 'DBG006',
       'DBG003', 'DMM005', 'DMM003_ref', 'DBG004', 'DMM004', 'DBG002',
       'DBG005_ref', 'DMM003', 'DBG004_ref', 'DBG002_ref', 'DMM004_ref',
       'DMM005_ref', 'DMM007_ref', 'DBG005', 'DBG001_ref', 'DBG007_ref',
       'DBG006_ref', 'DBG007'], dtype=object)

In [27]:
duplexes = list(duplexes)
n_exp = np.ceil(len(duplexes) / 6).astype(int)
sample_sheet = pd.DataFrame(columns=['curve_date', 'TODO', 'curve_num',# 'BlankTo', 
                                    'SEQID', 'conc_uM', 'TotalVolume'])
for i in range(n_exp):
    seqs = duplexes[6*i:6*i + 6]
    seqs += ["blank"] * (7 - len(seqs))
    exp_dict = dict(
        curve_date = "duplex_run1_%02d" % (i+1),
        TODO = True,
        curve_num = np.arange(7, dtype=int) + 1,
        SEQID =  seqs,
        conc_uM = 10,
        TotalVolume = 300
    )
    df = pd.DataFrame(exp_dict)
    sample_sheet = pd.concat([sample_sheet, df], axis=0)
    
sample_sheet.to_csv("./data/uv_melt/ECLTables/ECLSampleSheet230310_10uM.csv")
sample_sheet

       curve_date  TODO curve_num         SEQID conc_uM TotalVolume
0  duplex_run1_01  True         1    DBG003_ref      10         300
1  duplex_run1_01  True         2  WC1025_split      10         300
2  duplex_run1_01  True         3        DBG001      10         300
3  duplex_run1_01  True         4     WC68_stem      10         300
4  duplex_run1_01  True         5        DBG006      10         300
5  duplex_run1_01  True         6        DBG003      10         300
6  duplex_run1_01  True         7         blank      10         300
0  duplex_run1_02  True         1        DMM005      10         300
1  duplex_run1_02  True         2    DMM003_ref      10         300
2  duplex_run1_02  True         3        DBG004      10         300
3  duplex_run1_02  True         4        DMM004      10         300
4  duplex_run1_02  True         5        DBG002      10         300
5  duplex_run1_02  True         6    DBG005_ref      10         300
6  duplex_run1_02  True         7         blank      10         300
0  duplex_run1_03  True         1        DMM003      10         300
1  duplex_run1_03  True         2    DBG004_ref      10         300
2  duplex_run1_03  True         3    DBG002_ref      10         300
3  duplex_run1_03  True         4    DMM004_ref      10         300
4  duplex_run1_03  True         5    DMM005_ref      10         300
5  duplex_run1_03  True         6    DMM007_ref      10         300
6  duplex_run1_03  True         7         blank      10         300
0  duplex_run1_04  True         1        DBG005      10         300
1  duplex_run1_04  True         2    DBG001_ref      10         300
2  duplex_run1_04  True         3    DBG007_ref      10         300
3  duplex_run1_04  True         4    DBG006_ref      10         300
4  duplex_run1_04  True         5        DBG007      10         300
5  duplex_run1_04  True         6         blank      10         300
6  duplex_run1_04  True         7         blank      10         300